version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test

      - run: yarn build

      - deploy:
          name: Deploy DEV
          command: yarn deploy
